export const Screen = {
    HOME_SCREEN:"HOME_SCREEN",
    NOTIFICATION_SCREEN: 'NOTIFICATION_SCREEN',
    PROFILE_SCREEN:"PROFILE_SCREEN",
    SIGN:"SIGN",
    DOCUMENT_SCREEN:'DOCUMENT_SCREEN',
    DOCUMENT_VIEW_SCREEN:'DOCUMENT_VIEW_SCREEN',
    PDF_VIEW:'PDF_VIEW',
}
